version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:0.95.4
    volumes:
      - /usr/local/docker/hass/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /usr/local/docker/letsencrypt/config/etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"
