homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Pacific/Auckland
  # Customization file
  customize: !include customize.yaml

# Load custom components
smartir:

# Enables the frontend
frontend:

# Enables system health
system_health:

# Enables the iOS App
ios:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

sensor: !include sensors.yaml
light: !include lights.yaml

climate:
  - platform: smartir
    name: Lounge Heat Pump
    unique_id: lounge_heat_pump
    device_code: 1024
    controller_send_service: !secret lounge_broadlink_send_packet
    temperature_sensor: sensor.temperature_158d00022cc700
    humidity_sensor: sensor.humidity_158d00022cc700
  - platform: generic_thermostat
    name: Bedroom Heater
    heater: switch.plug_158d000243119c
    target_sensor: sensor.temperature_158d000245ab2f
    min_temp: 16
    max_temp: 30
    min_cycle_duration:
      minutes: 1
    initial_operation_mode: "off"

# Plex server
media_player:
  - platform: plex
  - platform: smartir
    name: Lounge TV
    unique_id: lounge_tv
    device_code: 2000
    controller_send_service: !secret lounge_broadlink_send_packet
  - platform: smartir
    name: Lounge Home Theatre
    unique_id: lounge_home_theatre
    device_code: 2010
    controller_send_service: !secret lounge_broadlink_send_packet

device_tracker:
  - platform: nmap_tracker
    # DHCP Range
    hosts: !secret internal_dhcp_range
    home_interval: 10
    interval_seconds: 30
    consider_home: 180
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False

zone:
  - name: Work
    latitude: !secret work_latitute
    longitude: !secret work_longitude
    radius: !secret work_radius
    icon: mdi:briefcase

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret aqara_hallway_mac
      key: !secret aqara_hallway_key

switch:
  - platform: broadlink
    host: !secret broadlink_lounge_host
    mac: !secret broadlink_lounge_mac
    friendly_name: "Lounge IR Blaster"

# Incude additional files
automation: !include automations.yaml
script: !include scripts.yaml
group: !include groups.yaml
