# Hide unwanted items
sun.sun:
  hidden: true
sensor.cams_ipad_battery_state:
  hidden: true
sensor.cams_iphone_battery_state:
  hidden: true
sensor.aqara_illumination_hallway:
  hidden: true
binary_sensor.aqara_wall_switch_lounge_left:
  hidden: true
binary_sensor.aqara_wall_switch_lounge_right:
  hidden: true
binary_sensor.aqara_wall_switch_lounge_both:
  hidden: true
binary_sensor.aqara_button_lounge:
  hidden: true

# Hide unwanted Plex media players
media_player.camsmacminiinternalcamguiseconz_airtunes_speaker:
  hidden: true
media_player.computer_airtunes_speaker:
  hidden: true
media_player.cams_iphone_2:
  hidden: true
media_player.cams_iphone:
  hidden: true
media_player.cams_ipad:
  hidden: true
media_player.safari:
  hidden: true

sensor.weather_precipitation:
  friendly_name: Rainfall
  icon: mdi:water

sensor.weather_temperature:
  friendly_name: Temperature

sensor.weather_wind_direction:
  friendly_name: Wind Direction
  icon: mdi:sign-direction

sensor.weather_wind_speed:
  friendly_name: Wind Speed
  icon: mdi:weather-windy

# Bathroom temperature sensor
sensor.aqara_humidity_bathroom:
  friendly_name: Humidity Bathroom
sensor.aqara_pressure_bathroom:
  friendly_name: Pressure Bathroom
sensor.aqara_temperature_bathroom:
  friendly_name: Temperature Bathroom

# Lounge temperature sensor
sensor.aqara_humidity_lounge:
  friendly_name: Humidity Lounge
sensor.aqara_pressure_lounge:
  friendly_name: Pressure Lounge
sensor.aqara_temperature_lounge:
  friendly_name: Temperature Lounge

switch.aqara_plug_bedroom_heater:
  friendly_name: Bedroom Heater

light.aqara_gateway_light_hallway:
  friendly_name: Hallway Light

light.yeelight_lounge_central:
  friendly_name: Lounge Central
light.yeelight_lounge_right:
  friendly_name: Lounge Right
light.yeelight_lounge_left:
  friendly_name: Lounge Left
