people:
  name: People
  control: hidden
  entities:
    - person.campbell
    - input_boolean.cam_holiday
    - person.tim

lounge_lights:
  name: Lounge Lights
  entities:
    - light.yeelight_lounge_central
    - light.yeelight_lounge_right
    - light.yeelight_lounge_left

battery_status:
  name: Battery Status
  control: hidden
  entities:
    - sensor.cams_iphone_battery_level
    - sensor.cams_ipad_battery_level
    - sensor.lounge_button_battery
    - sensor.lounge_temp_battery
    - sensor.lounge_wall_switch_battery
    - sensor.bathroom_temp_battery

synology_stats:
  name: Trinity NAS
  control: hidden
  entities:
    - sensor.volume_used_volume_1
    - sensor.status_sda
    - sensor.status_sdb
    - sensor.status_sdc
    - sensor.status_sdd

external_weather:
  name: External Weather
  control: hidden
  entities:
    - sensor.weather_precipitation
    - sensor.day_night
    - sensor.weather_temperature
    - sensor.weather_wind_direction
    - sensor.weather_wind_speed

indoor_temps:
  name: Indoor Sensors
  control: hidden
  entities:
    - sensor.aqara_humidity_lounge
    - sensor.aqara_pressure_lounge
    - sensor.aqara_temperature_lounge
    - sensor.aqara_humidity_bathroom
    - sensor.aqara_pressure_bathroom
    - sensor.aqara_temperature_bathroom

Environment:
  view: yes
  name: Environment
  entities:
    - climate.lounge_heat_pump
    - group.indoor_temps
    - group.external_weather

media_scripts:
  name: Media Scripts
  entities:
#    - script: script.lounge_music

Media:
  view: yes
  name: Media
  entities:
    - media_player.camsmacminiinternalcamguiseconz
    - media_player.itunes
    - media_player.lounge_tv
    - media_player.lounge_home_theatre
