- name: Lounge normal
  entities:
    light.yeelight_lounge_central:
      state: on
      transition: "10"
      brightness: "255"
      kelvin: "3000"
    light.yeelight_lounge_left:
      state: on
      transition: "10"
      brightness: "255"
      kelvin: "3000"
    light.yeelight_lounge_right:
      state: on
      transition: "10"
      brightness: "255"
      kelvin: "3000"