- name: Lounge Normal
  entities:
    light.yeelight_lounge_central:
      state: on
      transition: "5"
      brightness: "255"
      kelvin: "3000"
    light.yeelight_lounge_left:
      state: on
      transition: "5"
      brightness: "255"
      kelvin: "3000"
    light.yeelight_lounge_right:
      state: on
      transition: "5"
      brightness: "255"
      kelvin: "3000"

- name: Lounge Dark
  entities:
    light.yeelight_lounge_central:
      state: off
      transition: "5"
    light.yeelight_lounge_left:
      state: off
      transition: "5"
    light.yeelight_lounge_right:
      state: off
      transition: "5"