# Weather prediction
- platform: yr
  name: Weather
#  forcast: 24
  monitored_conditions:
    - temperature
    - precipitation
    - windSpeed
    - windDirection

# Custom day/night icon
- platform: template
  sensors:
    day_night:
      friendly_name: 'Day/Night'
      value_template: '{% if is_state("sun.sun", "above_horizon") %}Day{% else %}Night{% endif %}'
      icon_template: '{% if is_state("sun.sun", "above_horizon") %}mdi:weather-sunny{% else %}mdi:weather-night{% endif %}'

# SSL certificate checker
- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 10800 #3 hours
  command: "/config/bin-external/ssl-cert-check/ssl-cert-check -b -c /etc/letsencrypt/live/dunedin.cam.guise.co.nz/cert.pem | awk '{ print $NF }'"

- platform: template
  sensors:
    lounge_button_battery:
      entity_id: binary_sensor.aqara_button_lounge
      value_template: "{{ states.binary_sensor.aqara_button_lounge.attributes.battery_level }}"
      friendly_name: 'Lounge Button Battery'
      device_class: battery
      unit_of_measurement: "%"

- platform: template
  sensors:
    lounge_temp_battery:
      entity_id: sensor.aqara_temperature_lounge
      value_template: "{{ states.sensor.aqara_temperature_lounge.attributes.battery_level }}"
      friendly_name: 'Lounge Temperature Battery'
      device_class: battery
      unit_of_measurement: "%"

- platform: template
  sensors:
    bathroom_temp_battery:
      entity_id: sensor.aqara_temperature_bathroom
      value_template: "{{ states.sensor.aqara_temperature_bathroom.attributes.battery_level }}"
      friendly_name: 'Bathroom Temerature Battery'
      device_class: battery
      unit_of_measurement: "%"

- platform: template
  sensors:
    lounge_wall_switch_battery:
      entity_id: binary_sensor.aqara_wall_switch_lounge_left
      value_template: "{{ states.binary_sensor.aqara_wall_switch_lounge_left.attributes.battery_level }}"
      friendly_name: 'Lounge Wall Switch Battery'
      device_class: battery
      unit_of_measurement: "%"
