title: Home Assistant
views:
  - title: Home
    path: home
    cards:
    
      - type: entities
        title: People
        show_header_toggle: false
        entities:
          - person.campbell
          - input_boolean.cam_holiday
          - type: divider
          - person.tim
          
      - type: entities
        title: Battery Status
        show_header_toggle: false
        entities:
          - sensor.cams_iphone_battery_level
          - sensor.cams_ipad_battery_level
          - sensor.lounge_button_battery
          - sensor.lounge_temp_battery
          - sensor.lounge_wall_switch_battery
          - sensor.bathroom_temp_battery
          
      - type: entities
        title: Trinity NAS
        show_header_toggle: false
        entities:
         - sensor.volume_used_volume_1
         - sensor.status_sda
         - sensor.status_sdb
         - sensor.status_sdc
         - sensor.status_sdd
         
  - title: Lighting
    path: lighting
    cards:
    
      - type: entity-filter
        entities:
          - group.all_lights
        state_filter:
          - "on"
        card:
          type: entities
          title: Lights Currently On
          show_header_toggle: true
          
      - type: entities
        title: Lounge Lights
        show_header_toggle: true
        entities:
          - light.yeelight_lounge_central
          - light.yeelight_lounge_right
          - light.yeelight_lounge_left
          
  - title: Environment
    path: environment
    cards: []
  - title: Media
    path: media
    cards: []
