title: Home Assistant
views:
  - title: Home
    path: home
    cards:
    
      - type: entities
        title: People
        show_header_toggle: false
        entities:
          - person.campbell
          - input_boolean.cam_holiday
          - type: divider
          - person.tim
          
      - type: entities
        title: Lounge Lights
        show_header_toggle: true
        entities:
          - light.yeelight_lounge_central
          - light.yeelight_lounge_right
          - light.yeelight_lounge_left
          
      - type: entities
        title: Battery Status
        show_header_toggle: false
        entities:
          - sensor.cams_iphone_battery_level
          - sensor.cams_ipad_battery_level
          - sensor.lounge_button_battery
          - sensor.lounge_temp_battery
          - sensor.lounge_wall_switch_battery
          - sensor.bathroom_temp_battery
          
  - title: Environment
    path: environment
    cards: []
  - title: Media
    path: media
    cards: []
