title: Home Assistant
views:
  - title: Home
    path: home
    cards:
    
      - type: entities
        title: People
        show_header_toggle: false
        entities:
          - person.campbell
          - input_boolean.cam_holiday
          - type: divider
          - person.tim
          
      - type: entities
        title: Battery Status
        show_header_toggle: false
        entities:
          - sensor.cams_iphone_battery_level
          - sensor.cams_ipad_battery_level
          - sensor.lounge_button_battery
          - sensor.lounge_temp_battery
          - sensor.lounge_wall_switch_battery
          - sensor.bathroom_temp_battery
          
      - type: entities
        title: Trinity NAS
        show_header_toggle: false
        entities:
         - sensor.volume_used_volume_1
         - sensor.status_sda
         - sensor.status_sdb
         - sensor.status_sdc
         - sensor.status_sdd
         
  - title: Lighting
    path: lighting
    cards:
    
      - type: entity-filter
        entities:
          - light.yeelight_lounge_central
          - light.yeelight_lounge_right
          - light.yeelight_lounge_left
          - light.yeelight_entryway
          - light.aqara_gateway_light_hallway
          - light.tv_backlight
        state_filter:
          - "on"
        card:
          type: entities
          title: Lights Currently On
          show_header_toggle: true
          
      - type: entities
        title: Lounge Lights
        show_header_toggle: true
        entities:
          - light.yeelight_lounge_central
          - light.yeelight_lounge_right
          - light.yeelight_lounge_left
      
      - type: entities
        title: Other Lights
        show_header_toggle: true
        entities:
          - light.yeelight_entryway
          - light.aqara_gateway_light_hallway
          - light.tv_backlight
          
  - title: Environment
    path: environment
    cards:
    
      - type: entities
        title: Indoor Sensors
        show_header_toggle: false
        entities:
          - sensor.aqara_humidity_lounge
          - sensor.aqara_pressure_lounge
          - sensor.aqara_temperature_lounge
          - sensor.aqara_humidity_bathroom
          - sensor.aqara_pressure_bathroom
          - sensor.aqara_temperature_bathroom
      
      - type: thermostat
        entity: climate.lounge_heat_pump
        
      - type: entity-button
        entity: switch.aqara_plug_bedroom_heater
        name: Cam Bedroom Heater
        tap_action:
          action: toggle
        hold_action:
          action: more-info
    
      - type: entities
        title: Bathroom Dehumidifier
        show_header_toggle: false
        entities:
          - input_boolean.bathroom_dehumidifier_status
          - sensor.aqara_humidity_bathroom
          - input_number.bathroom_dehumidifier_target_humidity
          - input_boolean.pause_bathroom_dehumidifier
          - timer.pause_bathroom_dehumidifier
          - entity: switch.aqara_plug_bathroom_dehumidifier
            name: Bathroom Plug
    
      - type: entities
        title: External Weather
        show_header_toggle: false
        entities:
          - sensor.weather_precipitation
          - sensor.day_night
          - sensor.weather_temperature
          - sensor.weather_wind_direction
          - sensor.weather_wind_speed
      
      - type: weather-forecast
        entity: weather.dark_sky
      
      - type: history-graph
        title: Indoor Temperatures
        entities:
          - entity: sensor.aqara_temperature_bathroom
            name: Bathroom
          - entity: sensor.aqara_temperature_lounge
            name: Lounge
    
  - title: Media
    path: media
    cards:
      - type: media-control
        entity: media_player.camsmacminiinternalcamguiseconz
      - type: media-control
        entity: media_player.lounge_home_theatre
      - type: media-control
        entity: media_player.lounge_tv
