title: Home Assistant
views:
  - title: Home
    path: home
    cards:
        # The markdown card will render markdown text.
      - type: entities
        title: People
        show_header_toggle: false
        entities:
          - person.campbell
          - person.tim
